allowBuilds:
  "@prisma/engines": true
  better-sqlite3: false
  electron-winstaller: true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
overrides:
  find-my-way: 9.7.0
  postcss: 8.5.22
  sharp: 0.35.3
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
